[profile.default]
solc = "0.8.30"
src = "src"
out = "out"
evm_version = "prague"
libs = ["dependencies"]

[lint]
exclude_lints = ["screaming-snake-case-immutable"]

[fuzz]
runs = 2048

[invariant]
runs = 20
depth = 1000
fail_on_revert = true

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
solady = "0.1.26"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
